const axios = require('axios');
const qs = require('qs');
const fs = require('fs');


// Ignore these brands
let exclude = [
    "Default Brand",
    "Adidas",
    "Babycham",
    "Bedroom Athletics",
    "Replay",
    "Levis",
    "Mbt",
    "ULace",
    "Ikon",
    "Sanita",
    "Loake",
    "Ecko",
    "Ravel",
    "Grendha",
    "Superdry",
    "Sugar",
    "Salt & Pepper",
    "Fifty-6",
    "Grafters",
    "Alegria",
    "Shoe String",
    "Woly",
    "Magnum",
    "Chasers",
    "Walkerland",
    "Art",
    "DC Shoes",
    "simple",
    "Irregular Choice",
    "Hush Puppies",
    "El Naturalista",
    "Rascal Shoes",
    "Fiorelli",
    "Rockport",
    "Base London",
    "Beach Athletics",
    "Emu Australia",
    "Bass",
    "G-star",
    "Moda In Pelle",
    "Wolverine",
    "Playboy",
    "Boxfresh",
    "Evisu",
    "Gola",
    "Pcs",
    "Diesel",
    "Energie",
    "Glth",
    "Holster",
    "East Pack",
    "Rocket Dog",
    "Keds",
    "Rubber Duck",
    "Monkfish",
    "Iron Fist",
    "Paul Frank",
    "Dunlop",
    "Happy Socks",
    "Chinese Laundry",
    "Logoshirt",
    "T.U.K",
    "Jeffrey Campbell",
    "Tom Ford",
    "Flossy",
    "Pepe Jeans",
    "Carrera",
    "Marc Jacobs",
    "Poetic Licence",
    "Jeffery West",
    "Hummel",
    "Frye",
    "XTI",
    "Phildon Footwear",
    "Sperry",
    "Kidderminster",
    "Nanny State",
    "Aquapac",
    "Gant",
    "Mi-Pac",
    "Swanky Swans",
    "Punch",
    "Boston",
    "Etnies",
    "Mocks",
    "Cheaney",
    "Storm London",
    "Red Or Dead",
    "Barker",
    "Macbeth",
    "Defonseca",
    "Gandys",
    "Alexander Mc Queen",
    "Gucci",
    "PRIMADONNA",
    "Supra",
    "Geox",
    "Rat Shoes",
    "Falke",
    "Burlington",
    "Frank Wright",
    "Cute To The Core",
    "United Nude",
    "Boulevard",
    "Zandra Rhodes",
    "Shellys London",
    "Red Tape",
    "Viento Americano",
    "Crep Protect",
    "J.G. Harrisons",
    "JUJU Jellies",
    "Start-Rite",
    "Lelli Kelly",
    "Oliver Sweeney",
    "French Connection",
    "Canalletti",
    "Amblers Safety",
    "Converse Acc",
    "K-Swiss",
    "Strive",
    "Collonil",
    "Cherry Blossom",
    "Lloyd",
    "Le Chameau",
    "Franklin & Marshall",
    "The Pack Society",
    "Maruti",
    "Herschel Supply",
    "Brooks",
    "Hickies",
    "Plae",
    "Liquiproof",
    "Jack & Jones",
    "Laskaas",
    "Lemon Jelly",
    "Sprayground",
    "Roka",
    "MOSES",
    "Seavees",
    "TIM",
    "Sik Silk",
    "Good News",
    "Mahabis",
    "Doughnut",
    "Diadora",
    "Fjallraven",
    "Thomas Partridge",
    "Underground",
    "Comatoes",
    "Subu",
    "Nike",
    "Ellesse Accessories",
];

var ignoredBrands = exclude.map(brand => "'" + brand + "'").join(',');
var data = qs.stringify({
    'query': `"SELECT stkp.id as ID, sti.style_string as Size, stkp.name as Description, sti.style_string as Colour, sti.barcode as Barcode, sti.ref as SKU, stidp.price_rrp as RRP, stkb.name as Brand FROM stk_product stkp INNER JOIN stk_item sti ON stkp.id = sti.stk_product_id INNER JOIN stk_item_default_price stidp ON sti.id = stidp.stk_item_id INNER JOIN stk_brand stkb ON stkp.stk_brand_id = stkb.id WHERE stkb.name NOT IN (${ignoredBrands})"`
});

var config = {
    method: 'post',
    url: 'https://tuffnels.e-mps.co.uk/tl-odbc/api/getData',
    timeout: 300000,
    headers: { 
      'Content-Type': 'application/x-www-form-urlencoded', 
      'Connection': 'keep-alive',
      "Accept": "*/*"
    },
    data : data
};

let getData = async() => {
    const response = await axios(config);
    const data = await response.data;
    return data
};

module.exports = {
    getData
};
